### ISSUE TITLE
tgcf forwards all pictures inspite of using a whitelist filter

### ISSUE THREAD

**Issue by RebbePod** [aahnik/tgcf#104]
**Describe the bug**
When using a whitelist filter, it will still forward all pictures

**To Reproduce**
Use a whitelist text filter, and try sending a photo

**Expected behavior**
It shouldn't forward the picture unless it includes a tag with the keyword

**System information:**
Running on Heroku

**Comment by aahnik** [comment]
@RebbePod Please provide a screenshot

**Comment by RebbePod** [comment]
I can try, it's pretty self explanatory and would be hard to bring out in a screenshot.

**Comment by aahnik** [comment]
i have solved this problem @RebbePod 

make sure you have installed the latest version of tgcf 0.1.26 or above, to test it out.

**Comment by aahnik** [comment]
hi @RebbePod help tgcf grow!

please share with your friends and different telegram groups and channels and social media.

thank you

**Comment by RebbePod** [comment]
Thank you so much, what's the easiest way to update? (Using heroku)

**Comment by aahnik** [comment]
> what's the easiest way to update? (Using heroku)

create a fresh new deploy

**Comment by RebbePod** [comment]
Thanks. Confirmed it's working.
