### ISSUE TITLE
Discord Forward

### ISSUE THREAD

**Issue by ItsCEED** [aahnik/tgcf#112]
There are 2 ways to do this.

One:
Make a bot, that needs to join the server and choose a channel where to send the messages.

Two:
Setup a webhook to a certain channel, and send all the messages via Webhook to it (20 messages per minute limit), but this would be really fast to make with a plugin I believe.

**Comment by aahnik** [comment]
Hi @ItsCEED this is completely offtopic.

we are not dealing with discord here.
