### ISSUE TITLE
Trying to forward messages from long peer ID's raises "OverflowError: Python int too large to convert to SQLite INTEGER"

### ISSUE THREAD

**Issue by vmussa** [aahnik/tgcf#123]
**Bug description**
When trying to forward messages from sources whose ID's are too long an `OverflowError` is raised with the following message:

```
OverflowError: Python int too large to convert to SQLite INTEGER
```
The complete error message is here: [buginfo1.txt](https://github.com/aahnik/tgcf/files/6431876/buginfo1.txt)

Some groups and users don't have personalized URLs or usernames and, instead, can be identified by a long number, like the following: `941282734_16703767399832056981`. Although we can use the `phone_number` in the case of a user, I can't think of a similar workaround for the case of a group.

**To Reproduce**
1) Find a group or user without a username and use Telegram Web to get their ID. That will be the number at the end of the URL. 
2) Set this ID as the source of a forward task at `tgcf.config.yml`.
3) Run `tgcf past -l`. The error is raised.

**Expected behavior**
The messages should be forward despite the peer ID's length.

**System information:**
Ubuntu 20.04 running on top of WSL2.
tgcf 0.1.28
Python 3.8.5
pip freeze -> [buginfo2.txt](https://github.com/aahnik/tgcf/files/6431877/buginfo2.txt)

**Proposed solution**
Maybe there is a way to translate this long ID into some other smaller identifier. There could be some functionality to parse a Telegram Web URL of a group or username and transform it to this smaller identifier. Or maybe there is a way to change the SQLite database to something that can handle bigger numbers.

**Comment by aahnik** [comment]
hey this `long peer ID's ` is not supported. and I have no intention to support it.

use the chat id. get it from [userinfobot](https://telegram.me/userinfobot)

suppose you want to know the chat id of a particular chat (group/channel/indivual chat). open you telegram app, and forward one message from the chat to userinfobot. it will tell the chat id. use that chat id.

in future, username,link,phone no etc will be supported.

but long peer id, is not supported, and will not be supported.

**Comment by aahnik** [comment]
@vmussa telegram web app is damn bad.

use desktop app for windows/mac/linux or mobile app for android or ios
