### ISSUE TITLE
Feature to remove links and usernames from messages

### ISSUE THREAD

**Issue by rijeshkumar** [aahnik/tgcf#129]
Please add a plugin for automatically detecting and removing any kind of links from messages

**Comment by aahnik** [comment]
that's a good idea. but there are other features on the priority list.

If you know python and little bit of telethon library, you may try doing this

read more about plugins here :

- https://github.com/aahnik/tgcf/wiki/Plugins
- https://github.com/aahnik/tgcf/wiki/How-to-write-a-plugin-for-tgcf-%3F

**Comment by aahnik** [comment]
You can do this in many ways.

## using regex

For this, you need to learn regex. Or use google search to find what you want.

1. Use regex to match a pattern and blacklist it. (read [filtering](https://github.com/aahnik/tgcf/wiki/How-to-use-filters-%3F))
2. Use regex to replace patterns like URLs or usernames with some other text (may be blank text, that means removed)
(regex pattern can find URLs which start with `http` or `https` reliably. But in telegram just writing `something.com` is also  a link. Writing a regex that will match that is difficult. It may match sentence endings with fullstop, and new line starting without a space.) read [text replacement](https://github.com/aahnik/tgcf/wiki/Text-Replacement-feature-explained)

## format

You can change the text format to "code". Thus all links will be unclickable. read [formatting](https://github.com/aahnik/tgcf/wiki/Format-text-before-sending-to-destination)

**Comment by rijeshkumar** [comment]
Thanks for regex support. I created a regex pattern to find URLs starting with https:// or http://. Sharing it for those who need it. 
(https|http)(://)\\S+
Above regex can find every lines starting with https:// or http// and select that line till a space come.

(Note: double back slash before S needed only if u use yaml. In other cases single back slash is enough

**Comment by aahnik** [comment]
> (Note: double back slash before S needed only if u use yaml. In other cases single back slash is enough

Yup! Inside yaml, you need to escape the `\`, otherwise, yaml bura man jayga.

**Comment by aahnik** [comment]
To convert all `@username` to `username` just do 

```yaml
  replace:
    text:
      "\\s+(@(\\w+))\\s*": " \\2 "
    regex: true
```

(exception: this pattern will not apply to the first word of message if that starts with `@`)

![image](https://user-images.githubusercontent.com/66209958/121718241-b9f14480-caff-11eb-8e7e-8ad712cdc0ea.png)
![image](https://user-images.githubusercontent.com/66209958/121718267-c2497f80-caff-11eb-8ab1-9f6e4fda00c8.png)

**Comment by ghost** [comment]
Can anyone provide a regex to remove everyhting from caption except those lines that are ending with .mkv or .mp4
