### ISSUE TITLE
Add regex support

### ISSUE THREAD

**Issue by aahnik** [aahnik/tgcf#136]
having regex will enable more powerful text filtering and replacement.

regex will allow a generic solution to #129

**Comment by RebbePod** [comment]
Is this now included?

**Comment by aahnik** [comment]
read the wiki pages. yup regex is available (from [v0.2.5](https://github.com/aahnik/tgcf/releases/tag/v0.2.5) onwards). that's why this issue is closed. 

i made a release on github, and also announced in telegram channel.

see https://github.com/aahnik/tgcf/discussions/2 and https://github.com/aahnik/tgcf/discussions/212
