### ISSUE TITLE
Forward several chats located above and below the media

### ISSUE THREAD

**Issue by ghost** [aahnik/tgcf#220]
In the Telegram group I'm in, members upload a file or video and write a description of it in a chat below it. Like the Screenshot below.

![캡처](https://user-images.githubusercontent.com/52667667/123421890-6d763080-d5f8-11eb-8c52-ddbd213efc6c.JPG)

By the way, in our group, we have lively discussions every day. This is where the problem arises. Forwarding both files and chats would be too inefficient. 
(Too many unnecessary chats) 
I want to pass only the file and a description of it. All I need is a few chats 'above and below' a file or media.

So I'm asking @Aahnik to add related features.

Is it possible to set up to forward 5 chats above and below the file that TGCF sends (even if there is `nofile` in the `blacklist`)? It would be nice if this was offered as a selectable option.

I think there are probably quite a few people who need this feature. 
In Telegram groups, users often use chat instead of captions to describe media or files.

**Comment by aahnik** [comment]
This is a very custom feature that you need. Please contact me on telegram. https://aahnik.dev
