### ISSUE TITLE
messages forwarded two times if it has inline button

### ISSUE THREAD

**Issue by SHAliakbari** [aahnik/tgcf#227]
> but i have one problem, some messages forwarder two times , duplicate .

May be those messages were there two times, and later one was deleted in source. **It's impossible for tgcf to send a message twice.** YOU ARE MAKING SOME MISTAKE. Or may be, Telegram's servers, sent an update twice, accidentally in a rare case.

> I ran it with -l command 

what ? what do you mean ? what you ran ? speak details

I have already explained how to see logs for systemctl.

Read [this portion](https://github.com/aahnik/tgcf/wiki/Using-with-systemctl#running-via-systemctl) of the wiki. And in this answer https://github.com/aahnik/tgcf/discussions/219#discussioncomment-920558, I have already given links to two StackOverflow posts, that explain how to see full logs/live logs.

> is it possible to see what text forwarded ?

No, that is not logged.

_Originally posted by @aahnik in https://github.com/aahnik/tgcf/discussions/219#discussioncomment-931368_

**Comment by SHAliakbari** [comment]
the original message has two button . both link to a bot 

![image](https://user-images.githubusercontent.com/7825385/123608698-38462a00-d814-11eb-9012-8649eb415338.png)

**Comment by SHAliakbari** [comment]
I think i found out the cus . 

the source channel , first post a message , then delete it and resend it with buttons . 

is there any way to delete then sent message if source remove it ?

**Comment by tissole** [comment]
There is a setting in the script called delete_sync that when set to true does exactly what you ask, if a message is deleted in source chat is also deleted in destination chat. But it has some caveats. Check
https://github.com/aahnik/tgcf/wiki/How-to-configure-tgcf-%3F#schema
and also #232 for the limitations. In the future, all will be resolved by implementing persistent storage.
