### ISSUE TITLE
Caption text

### ISSUE THREAD

**Issue by mahdish45** [aahnik/tgcf#264]
Hi 
tgcf can write on the end message caption?
(add text end of forward message)

**Comment by tissole** [comment]
If you're asking for custom captions for files, is already planned for a future version, see #177

**Comment by aahnik** [comment]
![image](https://user-images.githubusercontent.com/66209958/209420391-c2660f8a-824d-4ced-9e96-ea05b8c3bdd1.png)


with the latest version of tgcf 1.1.8 or above, you can add header and footer captions to a message
