### ISSUE TITLE
Running multiple instances of tgcf does not work.

### ISSUE THREAD

**Issue by LightMoon** [aahnik/tgcf#286]
I am not sure if this project gets the support it deserves but I couldn't find a way to run multiple instances of tgcf which work properly.

I tried to install a few tgcf instances in separate virtual environments as I need to forward incoming messages base on keywords. Apparently, it is not feasible with passing different config files, so there was no other way to run different instances on a Linux virtual machine with the help of virtualenv.

I was hoping, I could achieve what I was after with that workaround, however, it didn't work. I noticed inconsistent results in which the live messages were even not getting process properly in that scenario.

Side note, things were working fine when I ran tgcf in past mode but this was/is not something that I was/am after.

**Comment by tissole** [comment]
If you have multiple accounts check #248, there's a guide there for Linux.

**Comment by LightMoon** [comment]
> If you have multiple accounts check #248, there's a guide there for Linux.

Why do we need a terminal multiplexer when we can run different instances with virtualenv ?

**Comment by tissole** [comment]
Virtualenv has not worked for you. Try multiplexer, maybe it will solve your problem.

**Comment by LightMoon** [comment]
I confirm that multiplexer doesn't work as well

**Comment by tissole** [comment]
Sorry to hear that. If your use case scenario is to have multiple pairs source-destination with their own plugins/filters, then your issue will be resolved when @aahnik will implement #176
