### ISSUE TITLE
The script is skipping files?

### ISSUE THREAD

**Issue by tissole** [aahnik/tgcf#29]
I run the script on my PC for 14-15 hours a day on 3 consecutive days and I managed to clone a channel. But after I realized that some files were skipped, a few hundred were missing from the destination channel. Do you have any idea why is this happening? There is a way to know if the script skips some files and to record which are those so we can copy them manually?

**Comment by aahnik** [comment]
Honestly, I have no idea of this. I will have to check.

Thanks @tissole  for informing.

**Comment by tissole** [comment]
Yeah, mostly big ones, videos and rar archives, hundreds of each, but some photos were skipped too, but only 12 of them. I have not encountered errors on my terminal, only when I checked from the Telegram client interface on each channel and compared the number o files, videos, photos, etc on each channel.

**Comment by tissole** [comment]
I have a hypothesis regarding "missing files". The error is probably caused by Telegram still counting the files deleted because of copyright in the source channel. Text messages that replace the deleted files ("file not available because of copyright") are wrongly counted as real files, videos, etc, but when those messages are copied in the destination channel the stats there are not counting them as real files.

**Comment by aahnik** [comment]
I think your hypothesis is true. but this is not possible to test.
