### ISSUE TITLE
Error In Handling Delete Message

### ISSUE THREAD

**Issue by Aniket-Code10010** [aahnik/tgcf#291]
When a message Is deleted in From Channel (Chat A)
The Bot does not the delete that msg in To Channel (Chat B) 

Edit Function is working Fine But Delete function doesn't 

Please See And fix it as soon as Possible
Waiting for Positive Reply 

Thank You

**Comment by rftghrt** [comment]
try to locate your `config.py` file and change

`delete_sync: bool = False`
to
[delete_sync: bool = True](url)

**Comment by Aniket-Code10010** [comment]
Bro I followed Your Instruction properly but it didn't work 
please help me with different solution

**Comment by tissole** [comment]
Your config file should look like this
https://nekobin.com/jadicayufe
Replace xxx and yyy with your chats IDs.
