### ISSUE TITLE
Reply not working on past (clone) messages during live mode

### ISSUE THREAD

**Issue by ariadarkkkis** [aahnik/tgcf#294]
Hi, I cloned a private channel that I'm not an admin to another private channel that I created. The problem I have is that in `tgcf live` if the source channel replies to an older message (before I run`tgcf` in live mode), it won't detect that this message was replied to. I already cloned the channel and already have that message in the destination channel ( I'm assuming even with same messageId ), but in live mode, it only replies to messages that have been sent and replied during the live mode.

Example:
The Source channel has 6 messages. I used `tgcf past` to clone 3 messages to the destination channel. Then I ran `tgcf live` to listen and copy messages. Then the source channel replies to its first message ( which is in the destination channel already ) but `tgcf` won't send the message as replied. it simply just copy and paste it. But if the source channel replies to message 5 (which has been sent to the destination channel during live mode), it will correctly detect the replied message and send the message in the destination channel as a reply to message 5.

**Comment by tissole** [comment]
Currently no, you have to manually forward them or use past mode. But there is a plan for implementing a database that will solve this issue.
