### ISSUE TITLE
Switch account, when flood wait limits one account for a long period of time

### ISSUE THREAD

**Issue by compunerd4** [aahnik/tgcf#30]
**Background**
When using the bot for large amounts of forwarding (thousands of messages and files each day), there is a floodwait enforced from the Telegram API. This floodwait varies and sometimes you can hit a long wait time of hours or a temporary suspension of 24 hours.

**Workaround**
If we have multiple Telegram Accounts, we can setup multiple Apps and API users / Bots. This means we can just delete the .forwardersession file and start again on another account.

**Request**
Enhance the Telegram Chat Forward bot to allow for it to alternate between various Telegram API users and .forwardersession files to avoid this ban. 

**Sample**
Viable option:
Have multiple api_id and hash stored in the .env file and anytime a floodwait error is over X amount of seconds (300 etc) then switch to the next api_id / hash in the file:
`api_id_1=302XXX`
`api_hash_1=7exxxxxxx`
`api_id_2=303XXX`
`api_hash_2=7fxxxxxxx`

**Comment by aahnik** [comment]
Fantastic idea.

Actually, I am restructuring the code for a lot of reasons. 

I will try to implement this feature in the new version.

**Comment by compunerd4** [comment]
Awesome, I look forward to the alternating feature 👍

**Comment by aahnik** [comment]
actually you dont need a seperate api id and API hash for using another account. You just need a separate phone number.

The way things are configured will change in future version. Everything will be easy to use, and manage

**Comment by rdsmiguel** [comment]
Hi Aahnik, how are you?
I want thank you for this wonderful project!
I discovered Telethon days ago, I will try create a channel to group news from many sources just for fun!
Your project reduced my final work a lot thank you!

I was reading the Telethon API to use bot instead API_ID and and API_HASH, I could send a message to any user name using bot.

bot = TelegramClient('bot', api_id, api_hash).start(bot_token=bot_token)
me = bot.get_me()
print(me)
bot.send_message(user_name,message)

But I can send a message using bot to a user_id, entity will be required:

ValueError: Could not find the input entity for <telethon.tl.types.PeerUser object at 0x7f47d6729d90>. Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.

I tried but same error
entity=bot.get_entity(user_id)
bot.send_message(entity,message)

ValueError: Could not find the input entity for <telethon.tl.types.PeerUser object at 0x7f95e18ec6a0>. Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.

Bot can't start a conversation, the weird part was be able to send using username, but there Telegram account with just id available :-(
Any idea?

**Comment by aahnik** [comment]
hi @rdsmiguel, your question is offtopic. please read telethon docs, or ask in telethon groups.

**Comment by aahnik** [comment]
hi @compunerd4 , please check out this feature #122, and as per this review #132 , this feature solves the problem of long flood waits.

**Comment by aahnik** [comment]
if you want to use multiple accounts, you need to do that manually. create two different folders. and create different sessions.

automatic client switching in the middle of forwarding will add unnecessary complexity.

after the introduction of custom_delay, you are less likely to face 1 day suspensions.
