### ISSUE TITLE
Error forwarding 1 message 2 times

### ISSUE THREAD

**Issue by Xulubu** [aahnik/tgcf#309]
Everything is fine except for one error: forward 1 message 2 times.
My source is a public channel (join only, no admin rights)
The destination is the group that I am an admin for
When the source has a message, it will be forwarded twice at the same time
I don't know how to fix it, please help, thanks!
[https://i.imgur.com/E0qVNaB.jpg](url)

**Comment by tissole** [comment]
Run `tgcf live --loud` and provide the log when the msgs are send twice.

**Comment by Xulubu** [comment]
Hi!
Yellow is a forwarded message from my channel to my group.
The other two messages are from another private channel (not me admin) to my group. It is duplicated.
[https://imgur.com/undefined](url)
