### ISSUE TITLE
Error Deploying to Heroku

### ISSUE THREAD

**Issue by RebbePod** [aahnik/tgcf#341]
**Describe the bug**
Heroku gives the following error
![image](https://user-images.githubusercontent.com/66928914/146431415-66017c3e-8987-4554-a0ec-db24c7cfb306.png)

**To Reproduce**
Followed the wiki

**Expected behavior**
expected it to deploy as normal

**Screenshots**
See above 

**System information:**
heroku

**Additional context**

**Comment by TKirtan** [comment]
Heroku blacklisted deploying method or code

**Comment by RebbePod** [comment]
> Heroku blacklisted deploying method or code

Why's that?

**Comment by TKirtan** [comment]
violates terms and conditions, overuse or abuse to their services kindo

**Comment by RebbePod** [comment]
> violates terms and conditions, overuse or abuse to their services kindo

Oh my, is that why my heroko instance isn't working?
How can I get it to work?

**Comment by danoscolaterais** [comment]
A way around is to fork to your account and deploy it from there.

**Comment by RebbePod** [comment]
> A way around is to fork to your account and deploy it from there.

Ok thank you I'm going to try that. The existing heroku instance I have also stopped working, is that related?
