### ISSUE TITLE
Multiple sources.

### ISSUE THREAD

**Issue by Amineratiba** [aahnik/tgcf#346]
Hi There, 
 
I would like to start with a thank you for this very nice script. It saves us paying for thrid party bots an expensive monthly subscription for a simple feature.

My question is regarding the config and its possible settings.
I was wondering if it was possible to set multiple sources at once? I know we can do that for destinations but unsure if it works for sources too.

Thanks in advance.

**Comment by denizkoele** [comment]
https://github.com/aahnik/tgcf/discussions/68

**Comment by Amineratiba** [comment]
Hi There, 

Thanks for the reply. 

I have done that, however, for some reason one of the two-channel I added is not working as expected.

**Comment by Amineratiba** [comment]
The issue seems to be related to the channel itself, not the multi sources/destinations 
Is there a way to figure out why ?

Thanks

**Comment by denizkoele** [comment]
Yes I think so too. The whole library doesn't work at all for me. With no channel.. The event listener doesnt get triggered. I thought it was because of the telegram update, but if this works at you. Then there must be a another bug

**Comment by Amineratiba** [comment]
It's weird, one channel works perfectly fine, but the second one doesn't at all...

**Comment by denizkoele** [comment]
Where did you deploy it? Or do you use it on your local?

**Comment by Amineratiba** [comment]
It's ran from my Laptop.
