### ISSUE TITLE
not working on a 200 members group

### ISSUE THREAD

**Issue by Frrinci99** [aahnik/tgcf#353]
**when i try to get past messages on a 200 member group it shows this message**

Invalid object ID for a chat. Make sure to pass the right types, for instance making sure that the request is designed for chats (not channels/megagroups) or     
otherwise look for a different one more suited\nAn example working with a megagroup and AddChatUserRequest, it will fail because megagroups are channels. Use InviteToChannelRequest  
instead (caused by GetHistoryRequest)

Also when i try to forward live messages from a group with 1k members it wont start it just stucks on the TGCF logo

**Comment by brunotguima** [comment]
i'm having the same issue, it was fixed?
