### ISSUE TITLE
Add partial forwarding setting to the web-ui

### ISSUE THREAD

**Issue by tissole** [aahnik/tgcf#369]
**Is your feature request related to a problem? Please describe.**
I want to be able to config partial forwarding from the web-ui. This option is not available to the UI.

**Describe the solution you'd like**
Add this option to the web-ui.

**Describe alternatives you've considered**
Make possible to configure the tgcf.config.json from the web-ui.

**Additional context**
I was able to do this only by manually adding these settings to the tgcf.config.json.

**Comment by aahnik** [comment]
" config partial forwarding" what is that ? which feature you want in web ui ?

**Comment by tissole** [comment]
#53

**Comment by aahnik** [comment]
Now, with the latest version of tgcf 1.1.8 or above you can do it

![image](https://user-images.githubusercontent.com/66209958/209419992-aba867ea-8704-41e4-91c7-2766a9ef9456.png)
