### ISSUE TITLE
Partial forwarding setting doesn't obey the range

### ISSUE THREAD

**Issue by tissole** [aahnik/tgcf#370]
**Describe the bug**
If partial forwarding is set like that
```
offset: 999
end: 1500
```
The script forwards from 1000 to 1501, so it does not stop at 1500, it forwards one more file (1501).

**To Reproduce**
Set up a partial forwarding from a chat.

**Expected behavior**
The script should stop after forwarding the last message indicated by `end:`

**System information:**
Ubuntu 22.04 under WSL.

**Comment by aahnik** [comment]
@tissole this is not a bug. This is how tgcf is designed. I will add this information in the docs, and also in the web UI, so that people can adjust their numbers.
