### ISSUE TITLE
Plugins per connections

### ISSUE THREAD

**Issue by tzagim** [aahnik/tgcf#381]
**Is your feature request related to a problem? Please describe.**
I make several connections at the same time and I want to apply certain plugins only to a specific connection or different plugins to different connections.

**Describe the solution you'd like**
That the plugins be per connection and not global.

By the way, you might want to allow each connection to be named.

Thank you very much for your work.

**Comment by aahnik** [comment]
hi @tzagim this is a very popular feature request, and there is already one issue to track its progress. i am closing this for being duplicate.

Refer #176
