### ISSUE TITLE
Track state of deleted posts after restart

### ISSUE THREAD

**Issue by yumupdate** [aahnik/tgcf#396]
**Is your feature request related to a problem? Please describe.**
Is it possible to track posts deletion even after tgcf restart in bot mode?

**Describe the solution you'd like**
Keep state of posts in db to able to monitor them for deletion.

**Describe alternatives you've considered**

**Additional context**
Forwarding posts to channels, tgcf crashing for some reason, restart tgcf and deletion old posts and expecting that tgcf delete them in destination channels

**Comment by aahnik** [comment]
this is already in my todo list. check #201
