### ISSUE TITLE
Splitting original post with 2 or more images to separeted posts 

### ISSUE THREAD

**Issue by yumupdate** [aahnik/tgcf#399]
**To Reproduce**
Send set of images in one post

**Expected behavior**
Same post (several images with caption in one post)

**Screenshots**
IN CHANNEL
![изображение](https://user-images.githubusercontent.com/82159969/207363092-52265f20-750d-4fea-9759-85a533c2651d.png)
OUT CHANNEL
![изображение](https://user-images.githubusercontent.com/82159969/207363175-b6540b9e-64aa-4c44-b26a-12e5e8ecb3a7.png)

**System information:**
Docker image with TGCF

**Additional context**
It must be checked also with plugins.

**Comment by aahnik** [comment]
I know this issue, and will fix it. Closing your issue, because its duplicate. Refer #96
