### ISSUE TITLE
The forwarded videos are not outputting sound, only the image

### ISSUE THREAD

**Issue by drikmrc** [aahnik/tgcf#407]
First I would like to congratulate you for the excellent work, it has helped me a lot.

I noticed that my videos are leaving without audio, only with the image. Is this a known or even resolved issue?

**Comment by drikmrc** [comment]
when doing some tests here, I noticed that the audio disappears only when the watermark is placed, a totally useful resource!!

**Comment by sybetjeh** [comment]
^^^I'm having the same problem here. Using a watermark makes the audio go away
