### ISSUE TITLE
TGCF App version issue

### ISSUE THREAD

**Issue by smartman0191** [aahnik/tgcf#410]
I have installed TGCF app version on Digital Ocean cloud. I'm seeing under Run tgcf is running latest version 1.1.8 but under advanced tab version and Platform is showing Running tgcf 1.1.7.post1. Also, tgcf is forwarding same message multiple time even no new message on group. 

Also, I have noticed below error message  on advanced tab configuration.

AttributeError: 'LiveSettings' object has no attribute 'sequential_updates'
Traceback:

File "/venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 564, in _run_script
    exec(code, module.__dict__)
File "/venv/lib/python3.10/site-packages/tgcf/web_ui/pages/6_🔬_Advanced.py", line 37, in <module>
    "Enforce sequential updates", value=CONFIG.live.sequential_updates

**Comment by aahnik** [comment]
this was fixed in tgcf 1.1.8

**Comment by favoritesG** [comment]
@aahnik How you instal 1.1.8 version on DigitalOcean?
Thanks
