### ISSUE TITLE
AUTOSTART TGCF process, when docker starts

### ISSUE THREAD

**Issue by jinx17** [aahnik/tgcf#429]
**Describe the bug**
When starting a docker container, everything works, except process does not start (it is stopped). 
A user can start it by geting into web settings, and click on RUN button.

**Expected behavior**
Everytime a docker is started, process **should be started automatically.** Only when doing some changes, a user should stop and run process within web interface with the RUN/STOP button.

**System information:**
Docker container.

**Comment by aahnik** [comment]
this issue is invalid.
running the docker container would start a tgcf, and you would get a user interface to configure and control start/stop of message forwarding connections

**Comment by mar-tusita** [comment]
@aahnik I suppose that this issue was intended to say "I'd like to the tgcf running on Docker automatically starts forwarding, just like the user push Run button after Docker container starts."
I also would grad to see tgcf has an option for that.

**Comment by aahnik** [comment]
Get it... Yup, I would add a option called autostart, that would attempt to start tgcf forwarding.

Would be useful in cases where server is restarted etc
