### ISSUE TITLE
tgcf-web command is not working

### ISSUE THREAD

**Issue by jebuskhoury** [aahnik/tgcf#433]
Hello, I'm trying to run tgcf-web and it's giving me this error:

/my-tgcf/.venv/lib/python3.11/site-packages/tgcf/web_ui
Usage: streamlit run [OPTIONS] TARGET [ARGS]...
Try 'streamlit run --help' for help.

Error: Streamlit requires raw Python (.py) files, but the provided file has no extension.
For more information, please see https://docs.streamlit.io

Is there anyway I can fix it ?

Thanks

**Comment by boshi19** [comment]
I also had this error, did you solve it?

**Comment by aahnik** [comment]
a proper installation, and usage of tgcf 1.1.8 and above would fix this
