### ISSUE TITLE
Please make a video on how to use tgcf on gitpod on your youtube channel. I'm from non tech background and want to save some educational videos that are channel restricted. Please help bro

### ISSUE THREAD

**Issue by sansarwadi** [aahnik/tgcf#437]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cerinawithasea** [comment]
I second this, i bet it would be very helpful to many of us who are novices and tired of getting stuck

**Comment by aahnik** [comment]
please check #538 
future version would be much easier to use and deploy for non-technical folks
