### ISSUE TITLE
add feature to forward message from forward restricted chat

### ISSUE THREAD

**Issue by zYxDevs** [aahnik/tgcf#467]
**Is your feature request related to a problem? Please describe.**
Unable to forward message from forward restricted chat.

**Describe the solution you'd like**
Using this method to forward message from forward protected chat.
If text: read the message text then send new message to new chat.
If media: get the media and read the caption (if any), download media it to local, send that downloaded media to new chat with same caption (if any).

**Comment by cold-nagai** [comment]
Adding such a feature is prohibited by ToS.
https://github.com/LonamiWebs/Telethon/issues/3237

**Comment by MobCode100** [comment]
You should close this issue now, we can't implement this, this is Telegram's restriction.
