### ISSUE TITLE
Getting Error Logs "rm: cannot remove 'logs_n_lines.txt': No such file or directory"

### ISSUE THREAD

**Issue by AbhayGhante** [aahnik/tgcf#468]
**Describe the bug**
I deployed it using venv on a vps, accessed the streamlit app through a ngrok tunneling service. Set Everything but After run the stream app shows everything working no errors. but when I see the linux terminal it shows error logs "rm: cannot remove 'logs_n_lines.txt': No such file or directory
rm: cannot remove 'logs_n_lines.txt': No such file or directory"

**To Reproduce**
Steps to reproduce the behavior: As I have described above

**Expected behavior**
Should Have Worked As Told

**Screenshots**
If applicable, add screenshots and gifs to help explain your problem.

**System information:**
In which OS are you running? GIve all details of where you have deployed the application. Make sure to give detailed version information.

**Additional context**
Logs of TGCF Streamlit app after RUN
tgcf
Running latest tgcf version 1.1.8

[07/07/23 19:35:06] INFO     Verbosity turned on! This is suitable for cli.py:57
                             debugging                                          
                    INFO     cryptg detected, it will be used for      aes.py:19
                             encryption                                         
                    INFO     tgcf.config.json detected!            config.py:109
                    INFO     config.py got executed                config.py:259
                    INFO     using bot account                     config.py:215
                    INFO     Connecting to                  mtprotosender.py:226
                             149.154.167.51:443/TcpFull...                      
[07/07/23 19:35:07] INFO     Connection to                  mtprotosender.py:277
                             149.154.167.51:443/TcpFull                         
                             complete!                                          
[07/07/23 19:35:08] INFO     Phone migrated to 5                    users.py:120
                    INFO     Reconnecting to new data  telegrambaseclient.py:709
                             center 5                                           
                    INFO     Disconnecting from             mtprotosender.py:317
                             149.154.167.51:443/TcpFull...                      
                    INFO     Disconnection from             mtprotosender.py:337
                             149.154.167.51:443/TcpFull                         
                             complete!                                          
                    INFO     Connecting to                  mtprotosender.py:226
                             91.108.56.109:443/TcpFull...                       
[07/07/23 19:35:10] INFO     Connection to                  mtprotosender.py:277
                             91.108.56.109:443/TcpFull                          
                             complete!                                          
[07/07/23 19:35:11] INFO     config.is_bot=True                      live.py:137
                    INFO     Command prefix is . for userbot and live_bot.py:136
                             / for bot                                          
                    INFO     Loaded admins are [1590151289]        config.py:206
                    INFO     Added event handler for new             live.py:148
                    INFO     Added event handler for edited          live.py:148
                    INFO     Added event handler for start           live.py:148
                    INFO     Added event handler for forward         live.py:148
                    INFO     Added event handler for remove          live.py:148
                    INFO     Added event handler for style           live.py:148
                    INFO     Added event handler for help            live.py:148
[07/07/23 19:35:12] INFO     From to dict is {-1001983685172:      config.py:199
                             [-1001547710980, 1590151289]}

**Comment by MobCode100** [comment]
can you try to create an empty logs_n_lines.txt file inside the tgcf directory?
