### ISSUE TITLE
bot success to deploy and running but the bot it not forward the message

### ISSUE THREAD

**Issue by Crukk11** [aahnik/tgcf#476]
**Describe the bug**
okie i just deploy as i follow the video of the instruction. then i setup all the info on the website then i just run the bot. the bot just  run fine when i try command the bot. it show the status but not forward the message

**To Reproduce**
Steps to reproduce the behavior: just deploy the script as usual then just run the bot at the website

**Expected behavior**
the bot not forward all the message but working fine on status command at the bot

**Screenshots**
![image](https://github.com/aahnik/tgcf/assets/64012867/6ee1fa91-7496-404e-a1af-5d778bc4ecf4)
![image](https://github.com/aahnik/tgcf/assets/64012867/4b2cd2cb-2f2f-429c-9c93-cf1a743921c5)
![image](https://github.com/aahnik/tgcf/assets/64012867/0371a154-d61b-4c58-a50b-1d9a41f2d7cc)
the message on third image is on the old bot fowarder. nothing came out from the new bot.
**System information:**
im using windows 11. deploy the sript on wsl (ubuntu 22.04.2 lts)

**Additional context**
btw i got error message on the ubuntu log it show this 
![image](https://github.com/aahnik/tgcf/assets/64012867/0e4f17b1-1d53-4ec2-be59-fb5bb9ed3748)
i dunno it got connection or not with the bug but just  it case maybe this error cause this problem.

**Comment by poliandro** [comment]
Try to put -100 before chat id
```
-1001620198712
-1001907214404
```

**Comment by Crukk11** [comment]
> Try to put -100 before chat id
> 
> ```
> -1001620198712
> -1001907214404
> ```

does it need to put source and the destionation too? 
cuz i try dat it not  working

**Comment by poliandro** [comment]
Try to change from bot to user. Bots have limitations.

**Comment by Crukk11** [comment]
> Try to change from bot to user. Bots have limitations.

can it use on live or just can set on past?

**Comment by poliandro** [comment]
In live mode you can use bot just between your own chats, because the bot must be a member and you can add your bots to the chats, but nobody will add your bots to their chats. With user you can use in live and past mode, but you must be a member in the chats, which is usually accepted.

**Comment by Crukk11** [comment]
okie thanks bro it work  already need to set it to user not the bot
