### ISSUE TITLE
User account can't find too old messages

### ISSUE THREAD

**Issue by MuhammadBayiz** [aahnik/tgcf#481]
**Describe the bug**
Hi! Got a bug/issue with this I'm using a user account to backup a group content the group has a proximitly 7 thousand videos and the IDs goes from 3 to 10466 i configured the offset and the end but when i run it it started at 4831 usually this is the case i tried other groups as well with huge number of files but same issue. Any ideas? Thanks in advance

**To Reproduce**
Forward messages from a huge group with other 10 thousand messages

**Expected behavior**
forward messages from ID N. 3 to ID N. 10466 with filtered messages to be forwarded

**System information:**
Ubuntu 20.04 running it on a podman container

**Additional context**
log of tgcf:
[log.txt](https://github.com/aahnik/tgcf/files/12239007/log.txt)

**Comment by MohamadBayz** [comment]
> I see that you're trying to forward only media files, do you get them all?

Yes that's right, it will filter out everything but videos photos documents.

**Comment by MobCode100** [comment]
Can you share me the link for the group? I might try to reproduce.

**Comment by MohamadBayz** [comment]
> Can you share me the link for the group? I might try to reproduce.

Uh... Why not, what's your username on TG the group is private so i need to send it in DM

**Comment by MobCode100** [comment]
> > Can you share me the link for the group? I might try to reproduce.
> 
> Uh... Why not, what's your username on TG the group is private so i need to send it in DM

Thank you for the thought, nevermind, I've found a channel that has a lot  of messages.

**Comment by MohamadBayz** [comment]
> 
> Thank you for the thought, nevermind, I've found a channel that has a lot of messages.

That's great, please let me know how it goes

**Comment by aahnik** [comment]
this is hard to reproduce for me, i think this is something to do with telegram's protocols, and the telegram client libraries i am using.... as this is not directly under tgcf's control am closing this.

**Comment by MuhammadBayiz** [comment]
Understandable, i think the problem were with the group message IDs the old messages had normal ids up until at a big number the numbers got reset and started again so definitely a telegram problem thanks for checking
