### ISSUE TITLE
Ping discord webhook on new private message in telegram account

### ISSUE THREAD

**Issue by Maxhem2** [aahnik/tgcf#484]
**Is your feature request related to a problem? Please describe.**
I'd really want my server to check my telegram account for new messages and then ping a webhook / signal or so

**Describe the solution you'd like**
A field to input my discord webhook and then a ping if a new message is received / good if telegram is used for selling

**Comment by aahnik** [comment]
this is out of scope of the current project. you may develop your own tgcf plugins to do so.
