### ISSUE TITLE
checkbox for replace group

### ISSUE THREAD

**Issue by panikajo** [aahnik/tgcf#485]
Make it possible to check the checkbox for groups of plugins. That is, for example, I want text to be fasted in one group and only pictures in the other.

**Comment by MobCode100** [comment]
I assumed you mean this feature, #482, #474 and #176. Please stop making duplicate issues.

**Comment by panikajo** [comment]
> I assumed you mean this feature, #482, #474 and #176. Please stop making duplicate issues.

yes but will it be added?

**Comment by MobCode100** [comment]
> > I assumed you mean this feature, #482, #474 and #176. Please stop making duplicate issues.
> 
> yes but will it be added?

Yes, it is under the todo tag, see #176.

**Comment by aahnik** [comment]
duplicate  #176 
will be fixed in #538
