### ISSUE TITLE
Running the program doesn't work.

### ISSUE THREAD

**Issue by lSyrexl** [aahnik/tgcf#490]
**Describe the bug**
When clicking on run it instantly stops and gives me this message after one second it goes back to normal.
![photo1691846013](https://github.com/aahnik/tgcf/assets/54649505/bdd83bf8-0355-4e51-908a-73c9f9234bf2)

**Expected behavior**
Should usually start and show me logs after reloading

**System information:**
Using RDP with Windows Server 2022

**Additional context**
Have account and connection added.

**Also this is what it says in console:**
```
"
The system cannot find the path specified.
The system cannot find the path specified.
'rm' is not recognized as an internal or external command,
operable program or batch file.
'tail' is not recognized as an internal or external command,
operable program or batch file.
'rm' is not recognized as an internal or external command,
operable program or batch file.
'tail' is not recognized as an internal or external command,
operable program or batch file."
```

**Comment by Wandrius** [comment]
I'm having the same problem here

**Comment by aahnik** [comment]
@lSyrexl @Wandrius You should deploy tgcf in a Linux environment. or if you are on windows, please use WSL. watch the videos given in README
