### ISSUE TITLE
Cannot install docker container

### ISSUE THREAD

**Issue by ChangeGod** [aahnik/tgcf#495]
**Describe the bug**

I cannot install the app through docker container

**To Reproduce**
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Expected behavior**

**Screenshots**
If applicable, add screenshots and gifs to help explain your problem.

**System information:**
Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

**Comment by MobCode100** [comment]
Your system is aarch64 not arm64

**Comment by ChangeGod** [comment]
> Your system is aarch64 not amd64, specify it like: `docker pull --platform linux/arm64 aahnik/tgcf`

I believe that the docker container is not support the platform :(
