### ISSUE TITLE
Feature Request - Automated Captioning Of Videos With Their Real Names

### ISSUE THREAD

**Issue by tissole** [aahnik/tgcf#55]
Many videos in TG channels are not captioned even if they have names that are only visible when you open the video. Even worse, they are uploaded in random order. If someone wants to watch a course with 70 videos have to open each video to search for the first one and then the second etc. Very annoying! 

It would make life much easier if the script could auto-captioning files with their names when forwarding.

**Comment by aahnik** [comment]
Wow! fantastic idea. would implement it.

**Comment by tissole** [comment]
Great! Thank You!

**Comment by aahnik** [comment]
this has been moved to #177
