### ISSUE TITLE
Redirection not working

### ISSUE THREAD

**Issue by superbonaci** [aahnik/tgcf#553]
The program seems to be working perfectly, I've added the API ID, API HASH bot token, set the connections, start , etc. but no messages get redirected.

How can I debug this further?

**Comment by favoritesG** [comment]
same for me :(

**Comment by superbonaci** [comment]
@favoritesG maybe redirection from a private channel needs user bot. Did you find out any other software that is currently working?

**Comment by favoritesG** [comment]
@superbonaci I updated to version 1.1.8, but it still doesn't work. But maybe the problem is in DigitalOcean after all. I'll probably try it from my desktop
There are paid versions of Auto_Forward_Messages_bot. The problem is more than not that you have to give 100% access to Telegram. The price depends on what you want from this application. I'm currently using this

**Comment by favoritesG** [comment]
@superbonaci When I added the bot as an admin to the group I want to copy, it started working. but I can't do that for groups I don't own...

**Comment by superbonaci** [comment]
@favoritesG I found out that it works even to redirect from private channels (invite only), if I have account type as `User` instead of `Bot`. Maybe it's the setting that has to be used for everything, probably something changed in server side.

![telegram-login](https://github.com/aahnik/tgcf/assets/8339596/41226876-fd8e-47f8-a98b-4a266478eddc)

Confirm me that it works for you as well and I'll close this issue.

**Comment by favoritesG** [comment]
@superbonaci interesting, I dont know how to get session string? where to enter api id, api hash, and phone nomber to generate session string.

what to do here:
![image](https://github.com/aahnik/tgcf/assets/115794435/a0184171-de45-4a4f-b514-66aca0e51262)


You can close this issue if you want.

**Comment by ghost** [comment]
After you install tg-login, you have to run the script with command python tg-login, then the script will ask you for details like api id, api hash, phone number and cloud password, and then will generate session string and send it to your Saved Messages.

**Comment by superbonaci** [comment]
@favoritesG 
Use https://github.com/aahnik/tg-login to get the session string, which is the last vale shown. The other you you need to register a new API in your telegram account https://my.telegram.org/ which are the first two.

Then configure as User and in Run tab click the Run red button. Put log to 1000 lines and see that works.
