### ISSUE TITLE
Offset is not updating in tgcf.config.yml

### ISSUE THREAD

**Issue by ankit-sinha-18** [aahnik/tgcf#62]
I checked the recent release of `tgcf` 
And tried both tgcf past and tgcf live feature
Both are working fine. But
When using tgcf in `past` mode , It is not updating it's offset in `tgcf.config.yml`

**Comment by aahnik** [comment]
Hi @ankit-sinha-18, this will be resolved today.

**Comment by ankit-sinha-18** [comment]
Thank you
