### ISSUE TITLE
Bug: stickers and emoji don't show who forwarded them

### ISSUE THREAD

**Issue by Reddog176** [aahnik/tgcf#71]
Stickers and single emoji just get posted from the tgcf user, with no text to show who originally posted them.

**Comment by aahnik** [comment]
hi, @Reddog176 Can you show me a screenshot?

**Comment by Reddog176** [comment]
![photo_2021-04-23_10-46-21](https://user-images.githubusercontent.com/14132051/115888761-48f7af80-a421-11eb-917c-0bfc6e17a5ff.jpg)
![photo_2021-04-23_10-46-25](https://user-images.githubusercontent.com/14132051/115888773-4bf2a000-a421-11eb-991d-dea9c5e310bb.jpg)
Attached screenshots from both the from and to sides. The GIF  in the middle forwarded proper.

**Comment by ankit-sinha-18** [comment]
This is not bug,, This is Telegram issue
Even if you manually forward sticker from any chat to any chat
It will not show forwarded tag.
Check yourself

**Comment by aahnik** [comment]
In your configuration, have you set `show_forwarded_from = true` ?

Is it working properly for normal text messages ?

Is the bug only for stickers and gifs ?

**Comment by aahnik** [comment]
Yup @ankit-sinha-18 . You are right

**Comment by Reddog176** [comment]
yes, show_forwarded_from is true, it's working for everything else. I'm aware it's a telegram issue. I expected the script to add a message either before or after to say who it was forwarded from.

**Comment by Reddog176** [comment]
Not a show stopper, just something to think about.

**Comment by aahnik** [comment]
this is not an important feature in my opinion.

If you need it badly, then implement a plugin that does this. [Learn how](https://github.com/aahnik/tgcf/wiki/How-to-write-a-plugin-for-tgcf-%3F)
