### ISSUE TITLE
Message not being forwarded to a bot, inspite of the client being a user.

### ISSUE THREAD

**Issue by aahnik** [aahnik/tgcf#73]
```shell
ValueError: Could not find the input entity for <telethon.tl.types.PeerChannel object at 0x7f638e3dc8b0>. Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more detail
```

**Comment by comienzo2093** [comment]
Hello, sorry I didn't understand well. Now is it possible for the tgcf to forward a message to the bot or to the user?

**Comment by aahnik** [comment]
@comienzo2093 don't worry about this.

tgcf will just work normally as expected.

Note:
- a bot cannot send message to another bot
- a user can send message to another bot

tgcf can be used by a bot account or a user account.

client means what account is used to login to telegram , for tgcf.

suppose you want to forward messages from a group or channel to another group or channel it will work.

but, if you wanted to forward from a source to a bot, then it failed (earlier)

but now the issue is fixed

**Comment by comienzo2093** [comment]
> @comienzo2093 don't worry about this.
> 
> tgcf will just work normally as expected.
> 
> Note:
> 
> * a bot cannot send message to another bot
> * a user can send message to another bot
> 
> tgcf can be used by a bot account or a user account.
> 
> client means what account is used to login to telegram , for tgcf.
> 
> suppose you want to forward messages from a group or channel to another group or channel it will work.
> 
> but, if you wanted to forward from a source to a bot, then it failed (earlier)
> 
> but now the issue is fixed


I understood it and checked a little while ago and it works completely. Thanks for the detailed answer.
