### ISSUE TITLE
Can I send message to 'saved message'?

### ISSUE THREAD

**Issue by comienzo2093** [aahnik/tgcf#81]
Hello, can I set 'Saved message' as the destination? Thank you.

**Comment by ankit-sinha-18** [comment]
Yes, Put you Telegram Id in destination ID

**Comment by comienzo2093** [comment]
> Yes, Put you Telegram Id in destination ID



> Yes, Put you Telegram Id in destination ID

Thank you. I'll try it now.

**Comment by comienzo2093** [comment]
> Yes, Put you Telegram Id in destination ID

Thanks, it works perfectly. It was my mistake not to erase -100.

**Comment by aahnik** [comment]
Hi @comienzo2093 and @ankit-sinha-18 you can send to "me".


Try it.

In your configuration file, it is no longer compulsory to use chat ids. You can use username, or link, or phone no.s

You can set `dest: [me]` to send to saved Messages.

Try and comment.

**Comment by comienzo2093** [comment]
> @ comienzo2093 및 @ ankit-sinha-18 안녕하세요 . "me"에게 보낼 수 있습니다.
> 
> 시도 해봐.
> 
> 구성 파일에서 더 이상 채팅 ID를 사용할 필요가 없습니다. 사용자 이름, 링크 또는 전화 번호를 사용할 수 있습니다.
> 
> `dest: [me]`저장된 메시지로 전송하도록 설정할 수 있습니다 .
> 
> 시도하고 의견을 말하십시오.

'dest: [me]'
It works. nice and easy!
