### ISSUE TITLE
Make delete sync optional

### ISSUE THREAD

**Issue by comienzo2093** [aahnik/tgcf#84]
Hello, I would like to request a feature. 

1. If I pass the message'hello' from A to B 
2. and then delete'hello' from A, 
3. it seems to be deleted from B as well. (sync function)

This feature is usually useful and convenient.
However, can I turn this feature off when I want to? I have set a group as source where chats are automatically deleted every minute, so there are some problems. Thank you:)

**Comment by aahnik** [comment]
It deletes in the destination chat ?

This sometimes does not work as telegram sometimes does not notify the client about message delete event.

I will add a feature to turn delete sync off.

But when delete sync is on, there is no guarantee that it will work. For your case it worked. Sometimes it doesn't.

**Comment by comienzo2093** [comment]
> It deletes in the destination chat ?
> 
> This sometimes does not work as telegram sometimes does not notify the client about message delete event.
> 
> I will add a feature to turn delete sync off.
> 
> But when delete sync is on, there is no guarantee that it will work. For your case it worked. Sometimes it doesn't.

Yes, It deletes in the destination chat. for me, it works well. 
I understood your words that 'there is no guarantee that it will work'. I just need to be able to turn it off, so it doesn't matter. Thank you.

**Comment by aahnik** [comment]
Hi @comienzo2093 why did you close this issue ?

This is not yet solved. Your requested feature is coming in the next release.


To help tgcf grow, please share about it on social media. Also star the repo, if you haven't already.

**Comment by comienzo2093** [comment]
> Hi @comienzo2093 why did you close this issue ?
> 
> This is not yet solved. Your requested feature is coming in the next release.
> 
> To help tgcf grow, please share about it on social media. Also star the repo, if you haven't already.

Sorry, I thought I should close after receiving the feedback. thank you for telling me.

**Comment by aahnik** [comment]
i have solved this problem @comienzo2093 

make sure you have installed the latest version of tgcf 0.1.26 or above, to test it out.

**Comment by aahnik** [comment]
hi @comienzo2093  help tgcf grow!

please share with your friends and different telegram groups and channels and social media.

thank you

**Comment by comienzo2093** [comment]
@aahnik 
It works very well. Thank you!
